packages:
  - apps/*
  - libs/*
  - libs/common/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - nestjs-pino
  - sharp
